Projectwebapp/Models/User.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Projectwebapp.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="กรุณาใส่ข้อมูล")]
        [RegularExpression(@"^64010462$|^6401047[5-6]$|^64010479$|^64010512$|^64010516$|^6401051[8-9]$|^64010522$|^64010526$|^64010529$|^64010543$|^64010546$|^64010552$|^6401057[4-5]$|^64010591$|^64010597$|^64010599$|^6401060[5-6]$|
        ^64010609$|^64010627$|^64010633$|^64010635$|^64010646$|^64010659$|^64010670$|^64010681$|^64010683$|^64010718$|^64010720$|^64010724$|^64010726$|^64010736$|^64010745$|^64010755$|^64010757$|^64010759$|^64010761$|^64010765$|^64010790$|
        ^64010792$|^64010801$|^64010806$|^64010808$|^64010813$|^64010815$|^64010818$|^6401082[3-4]$|^64010827$|^64010842$|^6401084[5-6]$|^64010850$|^64010860$", ErrorMessage = "ไม่มี Student ID นี้ใน sec19")]
        public string Secid { get; set; }
        [Required(ErrorMessage = "กรุณาใส่ข้อมูล")]
        [MaxLength(50)]
        public string Pass { get; set; }
        [Required(ErrorMessage = "กรุณาใส่ข้อมูล")]
        [Compare("Pass", ErrorMessage = "รหัสผ่านไม่ตรงกัน")]
        public string ConfirmPassword { get; set; }
    }
}

Projectwebapp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Projectwebapp.Models;
using System.Diagnostics;

namespace Projectwebapp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projectwebapp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projectwebapp.Data;
using Projectwebapp.Models;
using System.Security.Claims;//new
using Microsoft.AspNetCore.Authentication;//new
using Microsoft.AspNetCore.Authentication.Cookies;//new
using Microsoft.AspNetCore.Authorization;

namespace Projectwebapp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ProductDBcontext _db;

        public OrderController(ProductDBcontext db)
        {
            _db = db;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Menu1(Sender obj)
        {
            _db.Sender.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Thankyou");
        }
        public async Task<IActionResult> LogOut() //new 
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            return RedirectToAction("index", "User");
        }
        public IActionResult Waiting()
        {
            return View();
        }
        public IActionResult Thankyou()
        {
            return View();
        }
        public IActionResult Stores()
        {
            return View();
        }
        public IActionResult Menu1()
        {
            return View();
        }
        public IActionResult Menu2()
        {
            return View();
        }
        public IActionResult Menu3()
        {
            return View();
        }
        public IActionResult Menu4()
        {
            return View();
        }
        public IActionResult Menu5()
        {
            return View();
        }
        public IActionResult Menu6()
        {
            return View();
        }
        public IActionResult Menu7()
        {
            return View();
        }
        public IActionResult Menu8()
        {
            return View();
        }
        public IActionResult Menu9()
        {
            return View();
        }
    }
}

Projectwebapp/Controllers/SenderController.cs
using Microsoft.AspNetCore.Mvc;
using Projectwebapp.Models;
using Microsoft.AspNetCore.Authentication;//new
using Microsoft.AspNetCore.Authorization;

namespace Projectwebapp.Controllers
{
    [Authorize]
    public class SenderController : Controller
    {
        private readonly ProductDBcontext _db;

        public SenderController(ProductDBcontext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Sender> allproduct = _db.Sender;
            return View(allproduct);
        }
        public IActionResult Getorder(int? id)
        {
            if (id == null)
            {
                return NotFound("id is null");
            }
            var obj = _db.Sender.Find(id);
            if (obj == null) { 
                return NotFound("obj is null");
            }
            return View(obj);
        }
       
        public IActionResult Confirm(int? id)
        {
            if (id == null)
            {
                return NotFound("ID cannot be null.");
            }
            var obj = _db.Sender.Find(id);
            if (obj == null)
            {
                return NotFound(id);
            }
            _db.Remove(obj);
            _db.SaveChanges();
            return View();
        }
    }
}

Projectwebapp/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Projectwebapp.Data;
using Projectwebapp.Models;
using System.Security.Claims;//new
using Microsoft.AspNetCore.Authentication;//new
using Microsoft.AspNetCore.Authentication.Cookies;//new
using Microsoft.AspNetCore.Authorization;

namespace Projectwebapp.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDBcontext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserController(ApplicationDBcontext db, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _db = db;
        }
        
        public async Task<IActionResult> Index()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
                return View();
            return View();
        }
        public IActionResult Regis()
        {
            return View();
        }
        [Authorize]
        public IActionResult Home()
        {
            return View();
        }
        public IActionResult Profile() 
        {
            return View();
        }
        public IActionResult MadeBy()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Regis(User obj) { 
            if (ModelState.IsValid)
            {
                _db.Users.Add(obj);
                _db.SaveChanges();
                HttpContext.Session.SetString("UserId", obj.Id.ToString());
                return RedirectToAction("Index");
            }
            return View(obj);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Secid, Pass")] User loginUser)
        {
            var login = await _db.Users.FirstOrDefaultAsync(u => u.Secid == loginUser.Secid && u.Pass == loginUser.Pass);
            
            if (login != null)
            {
                HttpContext.Session.SetString("UserId", login.Secid.ToString());
                List<Claim> claims = new List<Claim>(){
                    new Claim(ClaimTypes.NameIdentifier,loginUser.Secid),
                    new Claim("OtherProperties","Example Role")
                };
                ClaimsIdentity claimsIdentify = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true
                };
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentify), properties);
                return RedirectToAction("Home");
            }
            else
            {
                ModelState.AddModelError("","Student ID หรือ Password ไม่ถูกต้อง");
            }
            
            return View(loginUser);
        }


    }
}

Projectwebapp/Views/User/Home.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<section class="vh-100 bg-image"
         style="background-image: url('https://1stcraft.com/wp-content/uploads/2022/02/1stcraft-cover-%E0%B8%9A%E0%B8%97%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1-food-delivery.jpg');background-size: cover;">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100 " style="color:coral">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                   <h1 class="text-uppercase text-center mb-5">Service</h1>
                    <h2 class="lead text-center mb-5">เลือกใช้บริการ</h2>
                    <div class="d-flex justify-content-center">
                        <a href="@Url.Action("Stores", "Order")" class="btn btn-warning btn-lg mx-3">คนสั่ง</a>
                        <a href="@Url.Action("Index", "Sender")" class="btn btn-warning btn-lg mx-3">คนซื้อ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Projectwebapp/Views/User/Index.cshtml
@model User
@{
    ViewData["Title"] = "Login";
}


<section class="vh-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 text-black">

                <div class="px-5 ms-xl-4">
                    <span class="h1 fw-bold mb-1" style="color:coral">Project MVC</span>
                </div>

                <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-3 pt-5 pt-xl-0 mt-xl-n5" style="color:coral">

                    <form method="POST" asp-controller="User" asp-action="Index" style="width: fit-content;">

                        <h3 class="text-uppercase mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>

                        <div class="form-outline mb-4">
                            <label asp-for="Secid" class="form-label" for="form2Example18">Student ID</label>
                            <input type="number"asp-for="Secid" id="form2Example18" class="form-control form-control-lg" />
                            
                        </div>

                        <div class="form-outline mb-4">
                            <label asp-for="Pass" class="form-label" for="form2Example28">Password</label>
                            <input type="text" asp-for="Pass" id="form2Example28" class="form-control form-control-lg" />
                            
                        </div>

                        <div class="pt-1 mb-4">
                            <button class="btn btn-info btn-lg btn-block" style="background-color:darkorange" type="submit">Login</button>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>

                        <p>ยังไม่มี account? สมัครสิ <a asp-controller="User" asp-action="Regis" class="link-info">Register here</a> </p>


                    </form>

                </div>

            </div>
            <div class="col-sm-6 px-0 d-none d-sm-block">
                <img src="https://i.pinimg.com/originals/eb/e6/07/ebe60767e7a111f23ee789ce338fcb7c.jpg"
                     alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
            </div>
        </div>
    </div>
</section>

Projectwebapp/Views/User/MadeBy.cshtml
@{
    ViewData["Title"] = "MadeBy";
}
<div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class=" container h-100">
        <h1 class="text-center " style="color:coral">ผู้จัดทำ</h1>
        <h1 class="text-center " style="color:coral">64010597 Phiphusana</h1>
        <h1 class="text-center " style="color:coral">64010646 Pawat</h1>
        <h1 class="text-center " style="color:coral">64010681 Phoom</h1>
        <h1 class="text-center " style="color:coral">64010724 Ratchapol</h1>
        <h1 class="text-center " style="color:coral">64010745 Lattapong</h1>
    </div>
</div>

Projectwebapp/Views/User/Profile.cshtml
@using Projectwebapp.Models;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.EntityFrameworkCore;
@using Projectwebapp.Data;

@inject IHttpContextAccessor HttpContextAccessor
@{
    
    ViewData["Title"] = "Profile";
}

<section class="vh-100 bg-image"
         style="background-image: url('https://wallpapercave.com/wp/wp4041567.jpg');background-size: cover;">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            @if (@HttpContextAccessor.HttpContext.Session.GetString("UserId")==null)
            {
                <div class="row d-flex justify-content-center align-items-center h-100 " style="color:coral">
                    <h1 class="text-center mb-5" style="font-size:80px;">คุณยังไม่ได้ login</h1>
                </div>
            }
            else
            {
                <div class="row d-flex justify-content-center align-items-center h-100 " style="color:coral">
                    <h1 class="text-center " style="font-size:80px;">StudentID:@HttpContextAccessor.HttpContext.Session.GetString("UserId")</h1>
                    <div class="d-flex justify-content-center">
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Projectwebapp/Views/User/Regis.cshtml
@model User
@{
    ViewData["Title"] = "Register";
}

<section class="vh-100 bg-image"
         style="background-image: url('https://th.bing.com/th/id/R.2896d0b4dd72756d37a07b757ec73492?rik=kNJXRhBwZ%2fLNRg&pid=ImgRaw&r=0');background-size: cover;">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100 " style="color:coral">
                <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                    <div class="card" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center mb-5">Register</h2>

                            <form method="POST" asp-controller="User" asp-action="Regis">

                                <div class="form-outline mb-4">
                                    <label asp-for="Secid" class="form-label" for="form3Example1cg">Student ID</label>
                                    <input type="number" asp-for="Secid" id="form3Example1cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Secid" class="text-danger"></span>
                                    
                                </div>

                                <div class="form-outline mb-4">
                                    <label asp-for="Pass" class="form-label" for="form3Example4cg">Password</label>
                                    <input type="text" asp-for="Pass" id="form3Example4cg" class="form-control form-control-lg" />
                                    <span asp-validation-for="Pass" class="text-danger"></span>
                                </div>

                                <div class="form-outline mb-4">
                                    <label asp-for="ConfirmPassword" class="form-label" for="form3Example4cdg">Repeat your password</label>
                                    <input type="text" asp-for="ConfirmPassword" id="form3Example4cdg" class="form-control form-control-lg" />
                                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                    
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body" style="background-color:darkorange">
                                        Register
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>